#!/bin/sh
if [ -a .commit ]
    then
    rm .commit
    git add $(git rev-parse --show-toplevel)/fme-guidance-image.coffee
    git add $(git rev-parse --show-toplevel)/spec/fme-guidance-image-spec.coffee
    git add $(git rev-parse --show-toplevel)/karma_tests.html
    git add $(git rev-parse --show-toplevel)/git-hooks/.
    git commit --amend -C HEAD --no-verify
fi
exit 0